---
output: github_document
---
   
<!-- README.md is generated from README.Rmd. Please edit that file --> 

Introducing ggprop.test, a micro package to teach about the logic of the prop test.

```{r, eval = F, echo = F, fig.width=12, fig.height=12}
library(ggprop.test)
snapshot <- ggplyr::intercept

donor |>
  ggplot() + 
  aes(x = decision) +
  geom_stack() + 
  geom_stack_label() + snapshot("p1") +
  geom_support() + snapshot("p2") +
  geom_prop() + 
  geom_prop_label() + snapshot("p3") +
  stamp_prop() + 
  stamp_prop_label() + snapshot("p4") +
  geom_normal_prop_null() + snapshot("p5") +
  geom_normal_prop_null_sds() + snapshot("p6") 


library(patchwork)
(p1 + p2) / 
(p3 + p4) /
(p5 + p6)  + 
  patchwork::plot_annotation(
    tag_levels = 1,
    title = "A prop test 'graphical poem' addressing the question: 
    
        For survey of 161 individuals on willingness to serve as 
        organ doners in the case of an accident, is there evidence
        that responses rate differs from a 50/50 split, 
        when 53 individuals respond 'no' and 108 individuals respond 'yes'?
      ",
    subtitle = "1. Draw bar chart (stacks) for each category.
2. Draw theoretical limits for proportion (0 to 1).
3. Calculate proportion and place (also the balancing point for stacks!).
4. Place null (look at the initial question, 'differs from 50/50' in this case)
5. Draw distribution for NULL, where SD = sqrt((p * (1-p))/n)
6. Calc z-score - where does observed prop fit into NULL distributions 
   (i.e. how many standard deviations fit between .5 and .67)"
                             ) &
  ggchalkboard:::theme_blackboard(base_size = 14) 


```



# Sketch and package
   

```{r, include = FALSE}
knitr::opts_chunk$set(      
  collapse = TRUE,
  warning = FALSE,  
  comment = "#>",
  message = F
)        

```

# The repo is just a bunch of experiments... 


```{r compute_for_prop_story, echo = F, message=F, warning=F}
library(statexpress)
library(tidyverse)

# 1. layer stack of bricks
compute_group_bricks <- function(data, scales, width = .2){
  
  data %>% 
    mutate(row = row_number()) %>% 
    mutate(y = row - .5) %>% 
    mutate(width = width)
  
}

# 2. layer label stack with count
compute_group_count <- function(data, scales){
  
  data %>% 
    count(x) %>% 
    mutate(y = n,
           label = n)
  
}


# 3. layer add x span
compute_scale <- function(data, scales){
  
  data %>% 
    summarise(min_x = min(x),
              xend = max(x),
              y = 0,
              yend = 0) %>% 
    rename(x = min_x)
  
}


# 4. layer add balancing point 
compute_xmean_at_y0 <- function(data, scales){
  
  data %>% 
    summarise(x = mean(x),
              y = 0, 
              label = "^") 
  
}

# 5. layer add balancing point value label
compute_xmean_at_y0_label <- function(data, scales){
  
  data %>% 
    summarise(x = mean(x),
              y = 0, 
              label = after_stat(round(x - 1, 2))) 
  
}



# 6. 
compute_panel_prop_asserted <- function(data, scales, null = .5){
  
  # stamp type layer - so ignor input data
  data.frame(y = 0, 
             x = null + 1,
             label = "^"
             )
  
}

compute_panel_prop_asserted_label <- function(data, scales, null = .5){
  
  # stamp type layer - so ignor input data
  data.frame(y = 0, 
             x = null + 1,
             label = round(null, 2)
             )
  
}

# Proposed layer composition
compute_dnorm_prop <- function(data, scales, null = .5,   dist_sds = seq(-3.5, 3.5, by = .1)
){
  
  n <- nrow(data)
  
  sd = sqrt(null * (1 - null)/n) # sd of the null distribution
  
  q <- dist_sds * sd + null
  
  data.frame(x = q + 1) %>%
    mutate(height = dnorm(q, sd = sd, mean = null)) %>%
    mutate(height_max = dnorm(0, sd = sd, mean = 0)) %>%
    mutate(y = .45*n*height/height_max) %>%  # This is a bit fragile...
    mutate(xend = x,
           yend = 0) %>% 
    # @teunbrand GeomArea$setup_data() requires a group column. Your panel computation does not preserve groups, but it should.
    mutate(group = 1) 
  
}  


# Proposed layer composition
compute_dnorm_prop_sds <- function(data, scales, null = .5,
  dist_sds = -4:4){
  
  n <- nrow(data)
  
  sd = sqrt(null * (1 - null)/n) # sd of the null distribution
  
  q <- dist_sds * sd + null
  
  data.frame(x = q + 1) %>%
    mutate(height = dnorm(q, sd = sd, mean = null)) %>%
    mutate(height_max = dnorm(0, sd = sd, mean = 0)) %>%
    mutate(y = .45*n*height/height_max) %>% # This is a bit fragile...
    mutate(xend = x,
           yend = 0)

}  




```



```{r prop_poem, echo = F, message = F, warning=F}
donor |>
  ggplot() +
  aes(x = decision) +
  # 1 geom_stack
  qlayer(geom = qproto_update(GeomTile, aes(color = "white")), 
         stat = qstat(compute_group_bricks)) +
  # 2 geom_stack_label() 
  qlayer(geom = qproto_update(GeomText, aes(vjust = 0)), 
         stat = qstat(compute_group_count)) +
  # 3 geom_xrange, show scale, range at y is zero
  qlayer(geom = GeomSegment, 
         stat = qstat_panel(compute_scale)) +
  # 4. geom_prop, show prop, i.e. balancing point
  qlayer(geom = qproto_update(GeomText, aes(size = 6, vjust = 1)),
         stat = qstat_panel(compute_xmean_at_y0)) + 
  # 5. geom_prop_label, labeling prop, balancing point
  qlayer(geom = qproto_update(GeomLabel, aes(fill = from_theme(colour %||% paper), label.size = NA, vjust = 0)),
         stat = qstat_panel(compute_xmean_at_y0_label))  +   
  # 6. stamp_prop, assertion, point
  qlayer(geom = qproto_update(GeomText, aes(size = 6, vjust = 1, color = from_theme(colour %||% accent))),
         stat = qstat_panel(compute_panel_prop_asserted)) +
  # 7. stamp_prop_label, assertion, label
  qlayer(geom = qproto_update(GeomLabel, aes(fill = from_theme(colour %||% paper), label.size = NA, vjust = 0, color = from_theme(colour %||% accent))),
         stat = qstat_panel(compute_panel_prop_asserted_label)) +
  # 8. geom_norm on prop plot
  qlayer(geom = qproto_update(GeomArea, aes(alpha = .2)),
         stat = qstat_panel(compute_dnorm_prop)) + 
   # 9. geom_prop_norm w/ sd marks
   qlayer(geom = qproto_update(GeomSegment, aes(linetype = "dotted")),
          stat = qstat_panel(compute_dnorm_prop_sds)) +
  labs(title = "Is there statistical evidence that choice to between being an\nan organ donar or not differs from 50/50") 
```



```{r prop_poem_functions, echo = F, message = F, warning=F}
geom_stack <- function(...){
  qlayer(geom = qproto_update(GeomTile, aes(color = "white")), 
         stat = qstat(compute_group_bricks), 
         ...)
  } 

geom_stack_label <- function(...){
  qlayer(geom = qproto_update(GeomText, aes(vjust = 0)), 
         stat = qstat(compute_group_count), 
         ...)
  } 

geom_support <- function(...){
  qlayer(geom = GeomSegment, 
         stat = qstat_panel(compute_scale), 
         ...)
  }

geom_prop <- function(...){
  qlayer(geom = qproto_update(GeomText, aes(size = 6, vjust = 1)),
         stat = qstat_panel(compute_xmean_at_y0),
         ...)
  }


geom_prop_label <- function(...){ 
  qlayer(geom = qproto_update(GeomLabel, 
                              aes(fill = from_theme(colour %||% paper), label.size = NA, vjust = 0)),
         stat = qstat_panel(compute_xmean_at_y0_label), 
         ...) 
  }

stamp_prop <- function(...){ 
  qlayer(geom = qproto_update(GeomText, aes(size = 6, vjust = 1, color = from_theme(colour %||% accent))),
         stat = qstat_panel(compute_panel_prop_asserted), 
         ...)
  }
  
  
stamp_prop_label <- function(...){  
  qlayer(geom = qproto_update(GeomLabel, 
                              aes(fill = from_theme(colour %||% paper), label.size = NA, vjust = 0, color = from_theme(colour %||% accent))),
         stat = qstat_panel(compute_panel_prop_asserted_label), 
         ...)
  }


geom_normal_prop_null <- function(...){
  qlayer(geom = qproto_update(GeomArea, aes(alpha = .2)),
         stat = qstat_panel(compute_dnorm_prop), 
         ...)
  } 


geom_normal_prop_null_sds <- function(...){
   qlayer(geom = qproto_update(GeomSegment, aes(linetype = "dotted")),
          stat = qstat_panel(compute_dnorm_prop_sds), 
          ...)
  }


theme_chalkboard <- function(...){
  
theme_classic(ink = alpha("lightyellow", .7),
           paper = "darkseagreen4", ...) + 
    theme(geom = element_geom(accent = alpha("orange", .9)))
  
}


```



```{r}
knitrExtra::chunk_to_dir("prop_poem_functions")
knitrExtra::chunk_to_dir("compute_for_prop_story")
```

```{r}
devtools::document()
devtools::check()
devtools::install(pkg = ".", upgrade = "never")
```

